---
title: "jobseq_details"
author: "Joy Baule"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(utHelpR)
library(janitor)
library(rlang)
```

Files pulled from JobsEQ are in the data folder.

CIP to Occuapation: CIP codes that are tied to occupation names for Washington County, Utah, and the US.

Awards: This is based on the number of awards from Utah Tech (reported as DSU in the JobsEQ system). The second tab of this spreadsheet is where I manually added SOC codes that match our CIP codes. 

```{r}
awards <- load_data_from_xlsx('Awards.xlsx') %>%
  row_to_names(1) %>% 
   clean_names()

#awards_clean <- awards[c(1:89), ] 
awards_clean <- rename_with(awards[c(1:88), ],  ~gsub("x4", "four_", .x))
```

```{r}
occupation_cips <- load_data_from_xlsx('CIP to Occupation.xlsx') %>%
  row_to_names(2) %>% 
  clean_names()
```

```{r}

occupation_cips_1 <- rename_with(occupation_cips, ~paste(.x, "wa", sep = "_"))

occupation_cips_2 <- rename_with(occupation_cips_1, ~gsub("_2_wa", "_ut", .x))

occupation_cips_3 <- rename_with(occupation_cips_2, ~gsub("_3_wa", "_us", .x))

occupation_cips_clean <- rename_with(occupation_cips_3[1:77, ],  ~gsub("x5_", "five_", .x)) %>% 
  rename(occupation = occupation_wa) %>% 
  rename(soc = soc_wa)

#View(occupation_cips_clean)
```

```{r}
occupation_cips_clean_df <- occupation_cips_clean %>% 
  mutate(cip_code = str_sub(occupation, 5, 11)) 
```

```{r}
both <- awards_clean %>% 
  left_join(occupation_cips_clean_df, by = c("cip_code" = "cip_code")) %>% 
  mutate(across(c(8:32), ~as.numeric(.x))) %>% 
  select(!occupation)
    #mutate_if(is.numeric, ~replace_na(., 0))
  
```

```{r}
just_wa_ <- both %>% 
  select(1:7, ends_with("_wa"))
```

```{r}
just_ut <- both %>% 
  select(1:7, ends_with("_ut"))
```

```{r}
just_us <- both %>% 
  select(1:7, ends_with("_us"))
```

```{r}
select_group_function <- function(input_df, x, y) {
  x <- rlang::enquo(x) 
  y <- rlang::enquo(y)  
  
output_df <- input_df %>% 
  select(1:7, ends_with(!!x)) %>% 
  filter((!!y) > 0)

return(output_df)
}
```

```{r}
just_ut_df <- select_group_function(both, "_ut", four_yr_awards) %>%
  filter(title == "Psychology, General") %>% 
  transpose()
  
just_test <- data.frame(unlist(just_ut_df))

```


```{r}
save(both, file = here::here("sensitive", "both.RData"))
```

